server:
  port: ${SERVICE_ORDER_PORT:8082}
  servlet:
    context-path: /order

spring:
  profiles:
    active: db
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${TRADE_USERNAME:trade.service.app@gmail.com}
    password: ${TRADE_GMAIL_PASS:sbimmaletiwxswin}