server:
  port: ${SERVICE_GATEWAY_PORT:8080}

spring:
  profiles:
    active: db

zuul:
  routes:
    retailment:
      path: /retailment/**
      url: http://localhost:8081/
    order:
      path: /order/**
      url: http://localhost:8082/
    admin:
      path: /admin-panel/**
      url: http://localhost:5000/